apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-app-statefulset
spec:
  selector:
    matchLabels:
      app: mypod
  serviceName: 'my-frontend'
  replicas: 1
  template:
    metadata:
      labels:
        app: mypod
    spec:
      containers:
        - name: my-frontend
          image: busybox
          args: # esto hay que utilizarlo siempre que pongamos busybox
            - sleep
            - infinity
          volumeMounts:
            - mountPath: '/data'
              name: pv-cris
  volumeClaimTemplates:
    - metadata:
        name: pv-cris
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: '5Gi'
        # storageClassName: do-block-storage , se hace en caso de trabajar con nubes externas
