apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      env:
        - name: MY_VARIABLE
          value: 'raul'
        - name: OTRA_VARIABLE
          value: 'raulmoya'
      resources:
        requests:
          memory: '64Mi'
        limits:
          memory: '128Mi'
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 60
        periodSeconds: 10
      ports:
        - containerPort: 80
